const FETCH_ERROR = 'FetchError'
const GRAPHQL_ERROR = 'GraphQLError'
const SCHEMA_VALIDATION_ERROR = 'SchemaValidationError'
const METHOD_NOT_ALLOWED_ERROR = 'MethodNotAllowedError'
const INVALID_SCHEMA_ERROR = 'InvalidSchemaError'
const MISSING_QUERY_PARAMETER_ERROR = 'MissingQueryParameterError'
const VALIDATION_ERROR = 'ValidationError'
const SYNTAX_ERROR = 'SyntaxError'
const INTROSPECTION_DISABLED_ERROR = 'IntrospectionDisabledError'

export {
    FETCH_ERROR,
    GRAPHQL_ERROR,
    INTROSPECTION_DISABLED_ERROR,
    INVALID_SCHEMA_ERROR,
    METHOD_NOT_ALLOWED_ERROR,
    MISSING_QUERY_PARAMETER_ERROR,
    SCHEMA_VALIDATION_ERROR,
    SYNTAX_ERROR,
    VALIDATION_ERROR,
}
